### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#59]
На production server-a също започнаха да валят OOME. От логовете изглежда да има някакъв проблем с асинхронните request-и от Apache HTTPClient библиотеката. Нещо се дъни и трябва да разберем какво преди release-a, иначе сървъра просто издиша.

```

2017-02-07 11:05:07,724 [ERROR] (Heartbeat.java:215)#run - Fatal hearbeat error!
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.start(CloseableHttpAsyncClientBase.java:83)
        at net.vexelon.currencybg.srv.remote.AbstractSource.getClient(AbstractSource.java:57)
        at net.vexelon.currencybg.srv.remote.AbstractSource.doGet(AbstractSource.java:64)
        at net.vexelon.currencybg.srv.remote.AbstractSource.doGet(AbstractSource.java:84)
        at net.vexelon.currencybg.srv.remote.FIBSource.getRates(FIBSource.java:87)
        at net.vexelon.currencybg.srv.Heartbeat.run(Heartbeat.java:157)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "OkHttp Dispatcher" java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-02-07 11:10:07,741 [INFO ] (Heartbeat.java:111)#run - Downloading rates from sources ...
2017-02-07 11:15:07,807 [INFO ] (Heartbeat.java:111)#run - Downloading rates from sources ...
2017-02-07 11:20:07,849 [INFO ] (Heartbeat.java:111)#run - Downloading rates from sources ...
2017-02-07 11:25:07,953 [INFO ] (Heartbeat.java:111)#run - Downloading rates from sources ...
2017-02-07 11:30:08,006 [INFO ] (Heartbeat.java:111)#run - Downloading rates from sources ...
Feb 07, 2017 11:30:21 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-bio-127.2.164.1-8080"]
Feb 07, 2017 11:30:21 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
*** CurrencyBG server shutdown ***
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/currencybg.server] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 1] but has failed to stop it. This is very likely to create a memory leak.
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 1] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 2] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 3] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 4] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-3-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 5] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 6] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 7] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 8] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-4-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 9] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 10] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 11] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 12] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-7-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 21] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 22] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 23] but has failed to stop it. This is very likely to create a memory leak.
....
```

```
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 308] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [Okio Watchdog] but has failed to stop it. This is very likely to create a memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/currencybg.server] created a ThreadLocal with key of type [org.apache.http.client.utils.DateUtils$DateFormatHolder$1] (value [org.apache.http.client.utils.DateUtils$DateFormatHolder$1@174e7b9]) and a value of type [java.lang.ref.SoftReference] (value [java.lang.ref.SoftReference@17ffa02]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Feb 07, 2017 11:30:21 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/currencybg.server] created a ThreadLocal with key of type [org.apache.http.client.utils.DateUtils$DateFormatHolder$1] (value [org.apache.http.client.utils.DateUtils$DateFormatHolder$1@174e7b9]) and a value of type [java.lang.ref.SoftReference] (value [java.lang.ref.SoftReference@1cd917c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

```

**Comment by petarov** [comment]
За съжаление този проблем отново се проявява. Нещо не е в ред със затварянето на връзките при теглене на валутите предполагам. Трябва още да се разузнае.

```

Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 184] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-53-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 205] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 206] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 207] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 208] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-58-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 225] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 226] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 227] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 228] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [pool-62-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 241] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 242] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 243] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/currencybg.server] appears to have started a thread named [I/O dispatcher 244] but has failed to stop it. This is very likely to create a memory leak.
Apr 29, 2017 11:48:32 AM org.apache.coyote.AbstractProtocol stop

```

**Comment by petarov** [comment]
Проблемът е трасиран до HttpClient класа `DefaultClientExchangeHandlerImpl<T>`


```java
@Override
    public void responseCompleted() throws IOException, HttpException {
        this.exec.responseCompleted(this.state, this);

        if (this.state.getFinalResponse() != null || this.resultFuture.isDone()) {
            try {
                markCompleted();
                releaseConnection();
                final T result = this.responseConsumer.getResult();
                final Exception ex = this.responseConsumer.getException();
                if (ex == null) {
                    this.resultFuture.completed(result);
                } else {
                    this.resultFuture.failed(ex);
                }
            } finally {
                close();  // ТУК
            }
        } else {
            NHttpClientConnection localConn = getConnection();
            if (localConn != null && !localConn.isOpen()) {
                releaseConnection();
                localConn = null;
            }
            if (localConn != null) {
                localConn.requestOutput();
            } else {
                requestConnection();
            }
        }
    }
```

--------

1. В случая при Тавекс parsing-a, тъй като пак са променили сайта, **jsoup** библиотеката обработва CSS заявката, но хвърля `RuntimeException`, тъй като не намира дата и час. 
2. `RuntimeException` се гълта silently при обработката на response-a, но поради някаква причина (трябва още инфо тук?) HTTP connection-a изглежда не се освобождава! 
3. Оттам и настъпват memory leaks на сървъра, които след време водят до `java.lang.OutOfMemoryError`. OO сървъра има само 512мб памет.
