### ISSUE TITLE
Tavex parsing failure

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#81]
@Tsvetoslav88 Изглежда пак има промени по сайта на Тавекс и имаме проблем с parse-инга.
Можеш ли да хвърлиш 1 око?

```
[ReporterHeartbeat] [TavexSource] Parse failed= java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at net.vexelon.currencybg.srv.remote.TavexSource.getTavexRates(TavexSource.java:90)
        at net.vexelon.currencybg.srv.remote.TavexSource$1.onRequestCompleted(TavexSource.java:113)
        at net.vexelon.currencybg.srv.remote.AbstractSource$1.completed(AbstractSource.java:98)
        at net.vexelon.currencybg.srv.remote.AbstractSource$1.completed(AbstractSource.java:1)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:432)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:325)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:267)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:123)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:164)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:339)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:317)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:278)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at net.vexelon.currencybg.srv.remote.TavexSource.getTavexRates(TavexSource.java:55)
        ... 18 more
```

------------

Явно, че при `RuntimeException` при обработката на валутите от източник имаме memory leak #59.  Отворих PR #80, който уж трябва да разреши проблема. Тези thread-ове се оказаха кошмарни леко. 😜

**Comment by Tsvetoslav88** [comment]
@petarov 
Това, което видях е, че чупят парсването на датата, но не видях никъде дата https://tavex.bg/obmen-na-valuta/, да не са я махнали тия пичове :)
Мисля, че беше някъде в дясно на страницата.

Дали да не я сетваме ние?

**Comment by petarov** [comment]
Май са махнали датата и часа. Да, ще трябва да процедираме подобно на Полана1.  Да я сетваме ние по текущи Europe/Sofia дата и час.

**Comment by Nutterum** [comment]
Здравейте,

Виждам, че имате желание да парсвате данни от нас? Може да сме ви полезни, ако кажете какво точно искате като инфо? Иначе, ако трябва да се гледат датите, ще бъдат отново добавени със следващия дев/дизайн пуш. 

Поздрави,
Екипът на Tavex

**Comment by petarov** [comment]
@Nutterum Здравейте!

В момента събираме информация за валутните курсове на Tavex [от тук](https://tavex.bg/obmen-na-valuta) на всеки час или два.  @Tsvetoslav88 Поправи ми ако греша.

Parse на html страниците по-принцип е тегаво. Ако е възможно да добавите по-нататък функционалност за извличане на текущите валутите в `json` формат,  то това определено ще улесни страшно много нещата и ще намали възможността за грешки. 👍 

Например нещо такова:

    GET https://tavex.bg/api/currencies.json

```json
HTTP/1.1 200 OK
Content-Type: application/json

{
  "last_update": "2017-05-29T18:16:35+02:00", 
  "currencies": [
    {
      "code": "EUR",
      "ratio": 1,
      "buy": "1.950",
      "sell: 1.958"
    },
    {
      "code": "USD",
      "ratio": 1,
      "buy": "1.740",
      "sell: 1.755"
    }
  ]
}
```

Благодарим за включването! 😎

**Comment by Nutterum** [comment]
Всъщност, извличане с json ще е скоро възможно. Ще пишем, когато имаме какво да предложим. Нямаме нищо против, да се ползват цените на валутите и продуктите ни стига да се спомене от къде се взимат.

Поздрави,
Екипът на Tavex

**Comment by petarov** [comment]
`json` би било супер! 

Имената на всички източници са посочени в приложението, в случая _Tavex България_. В последната версия сме добавили и меню `Обменни бюра`, където са посочени източниците и връзки към web адресите им.
